package exceptions;

public enum ExceptionCode {
    UNIDENTIFIED ("NIEZIDENTYFIKOWANY WYJATEK"),
    DB ("WYJATEK Z BAZY DANYCH"),
    REPOSITORY ("WYJATEK Z WARSTWY REPOZYTORYJNEJ"),
    SERVICE ("WYJATEK Z WARSWTY SERWISOWEJ"),
    VALIDATION ("WYJATEK OD WALIDACJI"),
    JSON("WYJATEK PLIKOW JSON"),
    BUILDER ("WYJATEK OD BUILDERA"),
    EMAIL("WYJATEK DOTYCZACY WYSYLANIA E-MAILI"),
    CATEGORIES("WYJATEK DOTYCZACY KLASY CATEGORY"),
    COUNTRIES("WYJATEK DOTYCZACY KLASY COUNTRY"),
    CUSTOMERS("WYJATEK DOTYCZACY KLASY CUSTOMER"),
    CUSTOMER_ORDERS("WYJATEK DOTYCZACY KLASY CUSTOMER_ORDER"),
    ERRORS("WYJATEK DOTYCZACY KLASY ERRORS"),
    PAYMENTS("WYJATEK DOTYCZACY KLASY PAYMENT"),
    PRODUCERS("WYJATEK DOTYCZACY KLASY PRODUCER"),
    PRODUCTS("WYJATEK DOTYCZACY KLASY PRODUCT"),
    SHOPS("WYJATEK DOTYCZACY KLASY SHOP"),
    STOCKS("WYJATEK DOTYCZACY KLASY STOCK"),
    TRADES("WYJATEK DOTYCZACY KLASY TRADE"),
    GUARANTEE_COMPONENTS("WYJATEK DOTYCZACY KLASY GUARANTEE COMPONENTS"),
    STATISTIC("WYJATEK Z WARSTWY SERVISOWEJ KLASY STYSTYCZNEJ"),
    ERRORS_STATISTIC("WYJATEK DOTYCZACY KLASY ERRORS_STATISTIC");

    private String description;

    ExceptionCode(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }
}
